version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

networks:
  covid-net:
    name: covid-net

services:
  reff:
    logging: *default-logging
    build:
      context: ./components/reff/
      dockerfile: ./Dockerfile
    container_name: reff
    volumes:
      - ./input:/covid19-reproductionNumber/input/
      - ./output:/covid19-reproductionNumber/output/
    networks:
      - covid-net

  rt:
    logging: *default-logging
    build:
      context: ./components/rt/
      dockerfile: ./Dockerfile
    container_name: rt
    volumes:
      - ./input/:/home/matlab/covid19-reproductionNumber/input/
      - ./output/:/home/matlab/covid19-reproductionNumber/output/
      - ./components/rt/src/:/home/matlab/covid19-reproductionNumber/src/
      - ${MATLAB_LICENSE}:/license.dat
    working_dir: /home/matlab/covid19-reproductionNumber
    environment:
      - MLM_LICENSE_FILE=/license.dat
    command: matlab -r "run('src/rt_estimator.m');"
    networks:
      - covid-net
