[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
